// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace DragDrop
{
	public partial class CollectionCell : UICollectionViewCell
	{
		public CollectionCell (IntPtr handle) : base (handle)
		{
		}

        public void setText(string text)
        {
            this.descriptionLabel.Text = text;
        }

		public void setPicture(string pictureName)
		{
			UIImage image = UIImage.FromBundle(pictureName);
			this.cellPicture.Image = image;
		}
	}
}
