// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace DragDrop
{
	public partial class TableCell : UITableViewCell
	{
		public TableCell (IntPtr handle) : base (handle)
		{
		}
	}
}
